app/blueprints/user.py
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    redirect,
    render_template,
    url_for,
)
from flask_login import current_user, login_required

from app.extensions import db
from app.forms import ProfileForm
from app.models import Talk, User

user = Blueprint("user", __name__)


@user.get("/<username>")
@login_required
def index(username):
    user = db.session.scalar(db.select(User).filter_by(username=username)) or abort(404)
    talks = db.paginate(
        user.talks.select().order_by(Talk.date.desc()),
        per_page=current_app.config["TALKS_PER_PAGE"],
    )
    return render_template("user/index.html", user=user, talks=talks)


@user.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    form = ProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash("Your profile has been updated.", "info")
        return redirect(url_for("user.index", username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.bio.data = current_user.bio
    return render_template("user/profile.html", form=form)

app/templates/user/index.html
{% extends 'base.html' %}{% from 'bootstrap5/pagination.html' import
render_pager %} {% block content %}
<div class="d-flex gap-3">
  <img width="196" src="{{ user.avatar(128) }}" alt="avatar" />
  <div>
    <h3>{{ user.username }}</h3>
    <p>{{ user.name }}</p>
    <p>{{ user.bio }}</p>
    {% if current_user == user %}
    <a href="{{ url_for('user.profile') }}" class="btn btn-primary"
      >Edit Profile</a
    >
  </div>
</div>
{% endif %} {% if talks.items | length %}
<div>{% include "talk/_talks.html" %}{{ render_pager(talks) }}</div>
{% else %}
<p>There is nothing here.</p>
{% endif %} {% endblock %}

app/templates/user/profile.html
{% extends 'base.html' %} {% from 'bootstrap5/form.html' import render_form %}
{% block content %}
<h3>Edit Profile</h3>
<div class="row"><div class="col-md-4">{{ render_form(form) }}</div></div>
{% endblock %}