app/blueprints/auth.py
from urllib.parse import urlsplit

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user

from app.extensions import db
from app.forms import LoginForm
from app.models import User

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("talk.index"))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.scalar(db.select(User).filter_by(username=form.username.data))
        if user is None or not user.check_password(form.password.data):
            flash("Invalid username or password", "danger")
            return redirect(url_for("auth.login"))
        login_user(user, remember=form.remember_me.data)
        next = request.args.get("next")
        if not next or urlsplit(next).netloc != "":
            next = url_for("talk.index")
        return redirect(next)
    return render_template("auth/login.html", form=form)


@auth.get("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("talk.index"))

app/blueprints/talk.py
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    redirect,
    render_template,
    url_for,
)
from flask_login import current_user, login_required

from app.extensions import db
from app.forms import CommentForm, PresenterCommentForm, TalkForm
from app.models import Comment, Talk

talk = Blueprint("talk", __name__)


@talk.get("/")
@login_required
def index():
    talks = db.paginate(
        db.select(Talk).order_by(Talk.date.desc()),
        per_page=current_app.config["TALKS_PER_PAGE"],
    )
    return render_template("talk/index.html", talks=talks)


@talk.route("/talk/new", methods=["GET", "POST"])
@login_required
def new_talk():
    form = TalkForm()
    if form.validate_on_submit():
        talk = Talk(
            title=form.title.data,
            description=form.description.data,
            slides=form.slides.data,
            video=form.video.data,
            venue=form.venue.data,
            venue_url=form.venue_url.data,
            date=form.date.data,
            author=current_user,
        )
        db.session.add(talk)
        db.session.commit()
        flash("The talk was added successfully.", "info")
        return redirect(url_for("talk.index"))
    return render_template("talk/new_talk.html", form=form)


@talk.route("/talk/<int:id>", methods=["GET", "POST"])
def get_talk(id):
    talk = db.get_or_404(Talk, id)
    comment = None
    if current_user.is_authenticated:
        form = PresenterCommentForm()
        if form.validate_on_submit():
            comment = Comment(
                body=form.body.data,
                talk=talk,
                author=current_user,
                notify=False,
                approved=True,
            )
    else:
        form = CommentForm()
        if form.validate_on_submit():
            comment = Comment(
                body=form.body.data,
                talk=talk,
                author_name=form.name.data,
                author_email=form.email.data,
                notify=form.notify.data,
                approved=False,
            )
    if comment:
        db.session.add(comment)
        db.session.commit()
        flash(
            "Your comment has been published."
            if comment.approved
            else "Your comment will be published after it's reviewed by the presenter.",
            "info",
        )
        return redirect(url_for("talk.get_talk", id=talk.id))
    comments = db.paginate(
        talk.comments.select().order_by(Comment.timestamp.asc()),
        per_page=current_app.config["COMMENTS_PER_PAGE"],
    )
    return render_template("talk/talk.html", talk=talk, form=form, comments=comments)


@talk.route("/talk/edit/<int:id>", methods=["GET", "POST"])
@login_required
def edit_talk(id):
    talk = db.get_or_404(Talk, id)
    if not current_user.is_admin and current_user != talk.author:
        abort(404)
    form = TalkForm()
    if form.validate_on_submit():
        form.to_model(talk)
        db.session.commit()
        flash("The talk was updated successfully.", "info")
        return redirect(url_for("talk.get_talk", id=talk.id))
    form.from_model(talk)
    return render_template("talk/edit_talk.html", form=form)


@talk.get("/moderate")
@login_required
def moderate():
    comments = db.paginate(
        current_user.for_moderation().order_by(Comment.timestamp.asc()),
        per_page=current_app.config["COMMENTS_PER_PAGE"],
    )
    return render_template("talk/moderate.html", comments=comments)


@talk.get("/moderate-admin")
@login_required
def moderate_admin():
    if not current_user.is_admin:
        abort(403)
    comments = db.paginate(
        current_user.for_moderation(True).order_by(Comment.timestamp.asc()),
        per_page=current_app.config["COMMENTS_PER_PAGE"],
    )
    return render_template("talk/moderate.html", comments=comments)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Talks{% endblock %}</title>
    {{ bootstrap.load_css() }}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom mb-4">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('talk.index') }}">Talks</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{{ url_for('talk.index') }}"
                >Home</a
              >
            </li>
            {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{{ url_for('user.index', username=current_user.username) }}"
                >Profile</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{{ url_for('talk.new_talk') }}"
                >New Talk</a
              >
            </li>
            {% set moderation_count = current_user.for_moderation_count() %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{{ url_for('talk.moderate') }}"
                >Moderate {% if moderation_count %}<span
                  class="badge text-bg-danger"
                  >{{ moderation_count }}</span
                >{% endif %}
              </a>
            </li>
            {% if current_user.is_admin %} {% set admin_moderation_count =
            current_user.for_moderation_count(True) %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{{ url_for('talk.moderate_admin') }}"
                >Moderate [Admin] {% if admin_moderation_count %}
                <span class="badge text-bg-danger"
                  >{{ admin_moderation_count }}</span
                >
                {% endif %}
              </a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{{ url_for('auth.logout') }}"
                >Logout</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{{ url_for('auth.login') }}"
                >Login</a
              >
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% for message in get_flashed_messages(with_categories=True) %}
      <div
        class="alert alert-{{ message[0] }} alert-dismissible fade show"
        role="alert"
      >
        {{ message[1] }}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endfor %}{% block content %} {% endblock %}
    </div>
    {{ bootstrap.load_js() }} {{ moment.include_moment() }} {% if
    current_user.is_authenticated %}
    <script>
      let token = '{{ current_user.get_api_token() | safe }}'

      async function comments_request(url, method, data = { token }) {
        await fetch(url, {
          method,
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(data),
        })
      }

      document.addEventListener('click', async event => {
        if (event.target.id === 'api-approve') {
          event.preventDefault()
          let { id } = event.target.dataset
          try {
            await comments_request('/api/comments/' + id, 'PUT')
            document.getElementById('moderate-' + id).style.display = 'none'
            document.getElementById('approved-' + id).style.display = ''
          } catch (error) {
            alert('Error: ' + error)
          }
        }
        if (event.target.id === 'api-delete') {
          event.preventDefault()
          let { id } = event.target.dataset
          try {
            await comments_request('/api/comments/' + id, 'DELETE')
            document.getElementById('moderate-' + id).style.display = 'none'
            document.getElementById('deleted-' + id).style.display = ''
          } catch (error) {
            alert('Error: ' + error)
          }
        }
      })
    </script>
    {% endif %}
  </body>
</html>